---
- name: Restart mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    daemon_reload: true
    enabled: true

- name: "Wait for {{ mongodb_net_port }} port"
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ mongodb_net_port }}"
    delay: 10
    timeout: 120
